# Generated by Django 2.2.1 on 2020-03-29 07:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoInfo',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('video_id', models.CharField(blank=True, max_length=1000, null=True)),
                ('title', models.CharField(blank=True, max_length=2000, null=True)),
                ('description', models.CharField(blank=True, max_length=5000, null=True)),
                ('published', models.CharField(blank=True, max_length=1000, null=True)),
                ('thumbnail', models.CharField(blank=True, max_length=5000, null=True)),
            ],
            options={
                'ordering': ('-published',),
            },
        ),
    ]
